#!/bin/bash

RET=0

for file in `find . -name "*.proto" -type f`; do
    A=$(diff -u $file <(clang-format $file))
    if [ "$?" == 1 ] ; then
        RET=1
        echo "$A"
    fi
done

exit "${RET}"
